### ISSUE TITLE
SVM Unexpected Performance

### ISSUE THREAD

**Issue by ryuga93** [kyamagu/mexopencv#243]
Hello, I am currrently doing Kernel PCA with SVM for face recognition and I am using the PCA code from the matlab community:
[http://www.mathworks.com/matlabcentral/fileexchange/39715-kernel-pca-and-pre-image-reconstruction](http://www.mathworks.com/matlabcentral/fileexchange/39715-kernel-pca-and-pre-image-reconstruction)

The problems I am currently facing is Matlab will close itself when I am using SVM/train() with high poly degree(3 and above) and could not write to XML file when the PCA poly is 3 or above with this error:
Unexpected Standard exception from MEX file.
```
What() is:C:\builds\master_PackSlave-win64-vc12-shared\opencv\modules\ml\src\svm.cpp:2038: error: (-212) SVM model data is
invalid, check sv_count, var_* and class_count tags in function cv::ml::SVMImpl::write
```

**Comment by amroamroamro** [comment]
I can't reproduce the error. Here is a simple test:

```matlab
X = [randn(50,3)+1; randn(50,3)-1];
Y = int32([ones(50,1); -ones(50,1)]);
model = cv.SVM();
model.Type = 'C_SVC';
model.KernelType = 'Poly';
model.Degree = 5;
model.train(X,Y);
out = model.save('.yml')
```

I get normal results for both XML or YML files:

``` yml
>> out
out =
%YAML:1.0
opencv_ml_svm:
   format: 3
   svmType: C_SVC
   kernel:
      type: POLY
      degree: 5.
      gamma: 1.
      coef0: 0.
   C: 1.
   term_criteria: { epsilon:1.1920928955078125e-07, iterations:1000 }
   var_count: 3
   class_count: 2
   class_labels: !!opencv-matrix
      rows: 2
      cols: 1
      dt: i
      data: [ -1, 1 ]
   sv_total: 15
   support_vectors:
      - [ -1.20647478e+00, 1.70146966e+00, 9.55046952e-01 ]
      - [ 4.44634289e-01, 4.53069359e-01, 1.46405131e-01 ]
      - [ 1.40720397e-01, 2.41152358e+00, -1.16633856e+00 ]
      - [ 6.91993773e-01, -1.52452314e+00, -1.57974973e-01 ]
      - [ 1.86273503e+00, -6.28384948e-03, 1.20139062e+00 ]
      - [ 6.60645902e-01, 3.38792890e-01, -9.76718724e-01 ]
      - [ 2.11010957e+00, 8.80508184e-01, -3.51432562e-01 ]
      - [ -2.10270405e+00, -6.47465214e-02, 1.56205678e+00 ]
      - [ 9.44574252e-02, 1.08114338e+00, -7.76994050e-01 ]
      - [ -1.60638261e+00, -6.98868513e-01, 6.55608438e-03 ]
      - [ -1.21575856e+00, 4.73418981e-01, 6.56834960e-01 ]
      - [ -1.34826541e+00, -4.00835335e-01, -6.61312938e-02 ]
      - [ 6.28963485e-02, 5.38209192e-02, -1.55770564e+00 ]
      - [ 8.70702386e-01, 1.38987936e-02, 3.48327532e-02 ]
      - [ 1.48267698e+00, -2.07794285e+00, -1.17626953e+00 ]
   decision_functions:
      -
         sv_count: 15
         rho: 9.1196728306453423e-02
         alpha: [ 2.4710137419353614e-01, 2.9076447102233669e-04,
             1.4607739941539860e-01, 2.0450507644703053e-03,
             3.4643462342999379e-02, 3.3874934513956989e-01,
             3.3825869312226692e-03, -1.3870656556536627e-03,
             -4.0797695404302625e-01, -7.2362795567962766e-03,
             -3.7832483828792049e-02, -3.5595753270749878e-04,
             -3.0507342858023823e-01, -3.2367687739775089e-03,
             -9.1910452870282693e-03 ]
```
